# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'fifty-fifty' do

pod 'Parse'
pod 'PayPal-iOS-SDK'

end

target 'fifty-fiftyTests' do

end

target 'fifty-fiftyUITests' do

end

